[theme]
base = "dark"
primaryColor = "#7c83f5"
backgroundColor = "#080a0f"
secondaryBackgroundColor = "#13161e"
textColor = "#e8eaf0"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 50
enableStaticServing = true

[runner]
fastReruns = true
